### ISSUE TITLE
App crashes when selecting "Transfer"

### ISSUE THREAD

**Issue by Stadicus** [neogeno/shango-lightning-wallet#10]
- OS (Android/iOS)   **iOS**
- Version of OS  **11.3.1**
- Device Make and Model   **iPad**
- Shango Version  **1.07 (10)**
- Device ID (Look in Settings-About Shango)  **8783434E-A0A1-4D06-A639-FF29B7A384E1**
- LND version    **lnd v0.4.2-beta**

When navigating in the App and selecting the "Transfer" button in the menu bar at the bottom, the app crashes to the OS.

## Expected Behavior
After selecting "Transfer", the corresponding screen should be shown.

## Current Behavior
Directly after tapping on "Transfer" the app crashes.

## Possible Solution or Best way to handle this problem
none to date

## Steps to Reproduce
1. Start app
2. Tap on "Transfer"

## Additional info
List of all payments, as shown by `lncli listpayments`  
https://pastebin.com/Z30GizFH

List of all invoices, as shown by `lncli listinvoices`  
https://pastebin.com/PZQepvJU

**Comment by neogeno** [comment]
This may be because of previous settings from older builds. Delete your old version from the device and re-install build number 12 or above. Thank you.

**Comment by Stadicus** [comment]
That solved the issues, previous Lightning and Bitcoin transactions are visible
