### ISSUE TITLE
Text is cropped on "Channels"

### ISSUE THREAD

**Issue by Stadicus** [neogeno/shango-lightning-wallet#11]
- OS (Android/iOS)   **iOS**
- Version of OS  **11.3.1**
- Device Make and Model   **iPad**
- Shango Version  **1.07 (10)**
- Device ID (Look in Settings-About Shango)  **8783434E-A0A1-4D06-A639-FF29B7A384E1**
- LND version    **lnd v0.4.2-beta**

I run the app on my iPad, so this might be a scaling or emulation issue.

## Expected Behavior
On the "Channels" screen, all text should be readable. 

## Current Behavior
The number of channels and remote balances are cropped at the right edge of the screen.

![img_0008](https://user-images.githubusercontent.com/19550140/41150779-1ebe20bc-6b0f-11e8-99ac-3fdcc405702d.jpg)

**Comment by neogeno** [comment]
Thanks for reporting this. Please delete your old app version and install build number 12 which has Native iPad support now.
