### ISSUE TITLE
Visual improvements

### ISSUE THREAD

**Issue by Stadicus** [neogeno/shango-lightning-wallet#15]
- OS (Android/iOS)   **Android**
- Version of OS  **8.0.0**
- Device Make and Model   **Samsung Galaxy S9**
- Shango Version  **Alpha Testing Build 6**
- Device ID **d340382c5ed4bfb5**

Two things caught my eyes:
* The "rotating bubbles" waiting image is shown with a shadow around its square edges
* The display of "sats" in the input field labled with ฿ is misleading. It makes me think of spending 150 BTC each time...

![screenshot_20180612-213417_shango](https://user-images.githubusercontent.com/19550140/41313385-197135a8-6e8a-11e8-97c6-a33dfe678b83.jpg)

## Possible Solution or Best way to handle this problem
* Remove the shadow from the "please wait" image
* Lable the amount field clearly as SAT

**Comment by neogeno** [comment]
The latest build replaces the Bitcoin symbol with a symbol someone decided was suitable to label Satoshis. Since there is no official one, that is what I used. In future releases, tapping that icon will cycle the values between, Satoshis, Bitcoin, US$ etc
