### ISSUE TITLE
Crash when opening channel

### ISSUE THREAD

**Issue by Stadicus** [neogeno/shango-lightning-wallet#16]
- OS (Android/iOS)   **Android**
- Version of OS  **8.0.0**
- Device Make and Model   **Samsung Galaxy S9**
- Shango Version  **Alpha Testing Build 6**
- Device ID **d340382c5ed4bfb5**
- LND version **lnd v0.4.2-beta**

## Expected Behavior
Open a new channel to this node (https://1ml.com/node/03d301eedc0949238bf919452ee7ef5c45bda4adbe17faba4037170b3573841446) with 300'000 sats (600'000 in wallet available).

## Current Behavior
Shortly after pressing on "Open Channel" the Android app crashes to the OS.

## Steps to Reproduce
1. Open Android app
1. Select "Channels"
1. Press (+)
1. Press "New channel"
1. Scan QR code from [this page](https://1ml.com/node/03d301eedc0949238bf919452ee7ef5c45bda4adbe17faba4037170b3573841446)
1. Enter capacity amount (I tried 300 and 300'000)
1. Leave Remote Deposit & Memo blank
1. Press "Open Channel"
1. App crashes

**Comment by neogeno** [comment]
Please try with zero in the Remote Deposit field - will be fixed in the next build

**Comment by Stadicus** [comment]
Works like a charm!
