### ISSUE TITLE
Crash when opening channel using iOS

### ISSUE THREAD

**Issue by BTCDCA** [neogeno/shango-lightning-wallet#18]
Thank you for trying out Shango Beta.  Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues. 

Please submit your issues with the following information

- OS (Android/iOS)   
- Version of OS  
- Device Make and Model   
- Shango Version  
- Device ID (Look in Settings-About Shango)  

iOS
11.4
iPhone 7 plus
0.4.2-beta
Device ID: 45EFBD76-E974-4E01-8C55-3594D9E71CB5

When I attempt to connect to a channel via the website : https://explorer.acinq.co/n/03a0df42e93655311fee911f857a5cf1c6415f395f6396bb5ac756cbc6f3532601 

the wallet crashes

Is there a different site I should navigate to when attempting to connect to a channel?

## Expected Behavior

I would think this would connect to any channel I choose.

## Current Behavior

The program crashes and I have to start over on the GUI

## Possible Solution or Best way to handle this problem

I have no idea.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by neogeno** [comment]
Please try with entering 0 in the Remote Deposit field

**Comment by BTCDCA** [comment]
I attempted this but there was an error:

We got a minor problem
2: error from GRPC Stream for openChannel: amount pushed to remote peer for initial state must be below the local funding amount

Please advise

**Comment by neogeno** [comment]
I know the error message is a bit weird but that's the one coming from LND so I can't change it for now. It just means you need to specify both the remote balance (how much if anything you want to push to other counteryparty) and also a channel capacity. Capacity should always be greater than 0. 

You can also try the latest build which fixes some bugs on this (Build 17 on ios)
