### ISSUE TITLE
Error: openchannel feerate_per_kw 250 below minimum 253

### ISSUE THREAD

**Issue by pseudozach** [neogeno/shango-lightning-wallet#19]
- Android   
- 8.1.0  
- Nokia 6 

## Expected Behavior
Channel parameters should be negotiated and transaction broadcasted. UI should reflect it.

## Current Behavior
App shows popup error 202: grpc stream for openchannel feerate_per_kw 250 below minimum 253

## Possible Solution or Best way to handle this problem
Known issue between LND <-> C-Lightning
find more info: https://www.mail-archive.com/lightning-dev@lists.linuxfoundation.org/msg00560.html
A fix was included in LND: https://github.com/lightningnetwork/lnd/issues/1330 so cloud LND should be updated to include this merge.

## Steps to Reproduce
1. Have on-chain balance in wallet
2. Open a channel to a c-lightning node (I tried my node: 029d8b53fe092eef79233655b9ef16e7e8ae9b7081670b0135357282d0dfba0bda@api.yunik.co:9735)

Thanks,

**Comment by neogeno** [comment]
thanks for the feedback - really appreciate the solution as well

**Comment by neogeno** [comment]
FYI: The latest build also allows you to specify a few when opening a channel.

**Comment by pseudozach** [comment]
It worked without setting a fee with the last version. thanks!

**Comment by neogeno** [comment]
found out there is also a bug with LND (not shango) when you try to open a channel with nodes running c lightning. will apply a patch when I can to fix it.

**Comment by neogeno** [comment]
All Shango nodes have been upgraded to lnd commit 8f68d0e6051646f426b0f09994aefad5da85ee54 now which has this fix in place
