### ISSUE TITLE
Crash after synched and it doesn't allowe to create a new channel 

### ISSUE THREAD

**Issue by hadnet** [neogeno/shango-lightning-wallet#2]
Installed Shango v1.07 (3) on my iPhone 6S iOS 11.4 and crashed a couple of times, then works and synched but after trying to use it crashed, again I need to close it and open it again and after two or three times works again, but I can't create a new channel or change settings (I can change the switch lnd server option only). I send a few satoshis to the receive address and works flawless, but can't create a new LN channel.

**Comment by hadnet** [comment]
In Shango 1.07 (4) when I click in New Payment memo/description icon it shows up a "0 SAT successfully sent via lightning incurring in 0 SAT fee" message even when I didn't make any transaction.

**Comment by hadnet** [comment]
When I tried to open Shango again it can not synched anymore (keeps saying "warning lnd not ready to use with no peers online yet"). The receive address is not showing the string address anymore, just the QR.

**Comment by neogeno** [comment]
Thank you please try again with build (6) which has just been released.
