### ISSUE TITLE
"Swipe state" of channels can freeze 

### ISSUE THREAD

**Issue by Stadicus** [neogeno/shango-lightning-wallet#20]
- OS (Android/iOS)   **Android**
- Version of OS  **8.0.0**
- Device Make and Model   **Samsung Galaxy S9**
- Shango Version  **Alpha Testing Build 6**
- Device ID **d340382c5ed4bfb5**

To manage channels, the individual channel can be swiped to the left. This works great most of the time, although it's not really clear this function even exists (could it be made more visible?). After using the app for some time, eg. opening and closing channels, it becomes very unresponsive.

## Expected Behavior
Channel swipe should always be possible without lag.

## Current Behavior
After some time, this function becomes unresponsive and the horizontal "swipe state" freezes from time to time. Vertical scrolling is not impaired, and a restart of the app fixes this issue.

See video demonstration:
https://vimeo.com/274971325

## Possible Solution or Best way to handle this problem
Restart app

**Comment by neogeno** [comment]
Thank you for spotting this. How many channels do you have open? I think I never saw this because I didn't open as many channels maybe?

**Comment by Stadicus** [comment]
17 Channels (9 active)

![2018-06-14 11_13_55-mtputty multi-tabbed putty](https://user-images.githubusercontent.com/19550140/41403017-1755c974-6fc4-11e8-9cbf-3fa71900f444.png)

**Comment by neogeno** [comment]
Fixed in build 18
