### ISSUE TITLE
Autopilot inconsistent and won't start

### ISSUE THREAD

**Issue by Aruk** [neogeno/shango-lightning-wallet#21]
- OS : Android   
- Version of OS  : 7.1.1
- Device Make and Model: Motorola - Moto X Play
- Shango Version : Alpha build 7
- Device ID (Look in Settings-About Shango) : 33d0d5b2e809458a

## Expected Behavior
The checkbox in setting should be consistent with the autopilot status in the main screen.

## Current Behavior
In node status, "No autopilot" is written. In the options the autopilot check box is checked. No channel is being created. If I try to uncheck the check box, after restart, the checkbox is still checked and there is no apparent effect.

Thank you for the great work!

**Comment by neogeno** [comment]
Hi, this is a bug/issue with LND not Shango and I've already raised it with the team. Once a patch/solution is told to me, I will apply it. In the meantime, I suggest you manually open the channels to Yalls and others for your testing.

Thank you for your patience.

**Comment by neogeno** [comment]
This has been fixed from build 25
