### ISSUE TITLE
No way to dismiss "Your node is hibernating" dialog

### ISSUE THREAD

**Issue by DrBeef** [neogeno/shango-lightning-wallet#22]
- OS: Android 8.0
- Galaxy S8
- Shango 1.0 
- I can't get my device ID as I can't get into the settings (see below)

I am trying to connect to my own node running on a raspberry pi. However I think somewhere along the line I did something wrong. I am now unable to recover the situation as everytime I start Shango it pops up the Your node is hibernating 30 second timeout, which repeats a couple of times (suggesting the docker node never comes out of hibernation). But because I don't want to use the docker node and it doesn't seem to ever wake up, when the counter gets to 0 the popup dialog remains and can't be dismissed, I have to kill the app through the Android apps menu.

## Expected Behavior
A simple dismiss button on the popup dialog so that I can get into app settings would be good

## Current Behavior
Please see above

## Possible Solution or Best way to handle this problem
A dismiss button, or "cancel node wake up" would be good

**Comment by Stadicus** [comment]
I also keep getting this display, which is quite annoying as I just want to connect to my own node, but have to wait for 30 seconds or so. A "cancel" button would be helpful, not getting this display when not connecting to AWS even better.
