### ISSUE TITLE
Channels are not shown on the channel page

### ISSUE THREAD

**Issue by bjarnemagnussen** [neogeno/shango-lightning-wallet#28]
- OS (Android/iOS)   Android
- Version of OS  8.1.0
- Device Make and Model   Xiaomi Redmi Note 4
- Shango Version  build 18
- Device ID (Look in Settings-About Shango)  6944746084732e5a

The list of channels does not appear on the channel page. It keeps showing only the loading graphic.

## Expected Behavior
The channel page should show a list if all channels (open/active/closing).

## Current Behavior
Stuck at the loading wheel graphic.

## Possible Solution or Best way to handle this problem
This newest build 18 may have broken the channel page fixing issue #25?

## Steps to Reproduce
1. Open channel page within Shango app.

**Comment by neogeno** [comment]
Please delete the old version and install the latest build number 20.
