### ISSUE TITLE
Pressing "total asset summary" crashes the app

### ISSUE THREAD

**Issue by bjarnemagnussen** [neogeno/shango-lightning-wallet#29]
- OS (Android/iOS)   Android
- Version of OS  8.1.0
- Device Make and Model   Xiaomi Redmi Note 4
- Shango Version  build 18
- Device ID (Look in Settings-About Shango)  6944746084732e5a

When pressing on the big circle showing "Total asset summary" on the main page crashes the app.

## Expected Behavior
I don't know what should be shown when pressing "Total asset summary".

## Current Behavior
Crashes the app.

## Steps to Reproduce
1. Press inside circle shoeing " Total asset summary".

**Comment by neogeno** [comment]
Please delete previous builds and install build 20
