### ISSUE TITLE
app crashes when "Connect"/"Disconnect" used

### ISSUE THREAD

**Issue by TomasHo** [neogeno/shango-lightning-wallet#3]
Thank you for trying out Shango Beta.  Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues. 

Please submit your issues with the following information

- OS (Android/iOS) -   iOS
- Version of OS  - 11.4
- Device Make and Model   iPhone 6S
- Shango Version  1.07
- Device ID (Look in Settings-About Shango)  1C66DAB2-F429-4F78-86D6-6A7A7EF7376A

## Expected Behavior

Confirmation message of succesful connection
## Current Behavior

App crashes to OS
## Steps to Reproduce

1. Open app, -> Settings, ->Switch LND Server
2. Enter IP address, scan Macaroon, scan TLS of a Raspibolt mainnet node
3. click Connect

OR

1. Open app, -> Settings, ->Switch LND Server
2. click Disconnect

**Comment by neogeno** [comment]
HI there, this has been corrected with build number 7. Please try again and let me know if the issue can be closed.

**Comment by TomasHo** [comment]
Yes, it does work now. Thanks.
