### ISSUE TITLE
Not able to enter new information after disconnecting from node

### ISSUE THREAD

**Issue by Stadicus** [neogeno/shango-lightning-wallet#30]
- OS (Android/iOS)   **Android**
- Version of OS  **8.0.0**
- Device Make and Model   **Samsung Galaxy S9**
- Shango Version  **Alpha Testing Build 20**
- Device ID **d340382c5ed4bfb5**

## Expected Behavior
On the "Connect LND Node" screen, when connected to my own node, I press the button "Disconnect", that should clear all input fields and I should be able to enter the new information and press "Connect".

## Current Behavior
When I press "Disconnect", the input fields are cleared but stay locked. The button still says "Disconnect". I cannot input any information and when I press "Disconnect" again, the error message "Invalid Input / Check TLS HEX certificate" appears.

## Possible Solution or Best way to handle this problem
At the moment, I need to exit the "Connect LND Node" screen and open it again. Then I can enter new connection information. Not a big deal, but it's an annoying bug that breaks the workflow.

**Comment by neogeno** [comment]
Noted. Thanks for the feedback. Did you problem with scanning the TLS codes go away now?

**Comment by neogeno** [comment]
resolved in build 23
