### ISSUE TITLE
ERROR from GRPC Stream for OpenChannel: peer is not connected

### ISSUE THREAD

**Issue by Stadicus** [neogeno/shango-lightning-wallet#31]
- OS (Android/iOS)   **Android**
- Version of OS  **8.0.0**
- Device Make and Model   **Samsung Galaxy S9**
- Shango Version  ** Alpha Testing Build 20**
- Device ID **d340382c5ed4bfb5**
- LND version    **lnd v0.4.2-beta**

## Expected Behavior
I would like to open a new channel to a specific node I looked up on 1ml.com:
https://1ml.com/node/02cf3cc45d8fee5055c4ba5a58fe22ae973685fa2cb43e2c5b6454eaa1d08066a8

## Current Behavior
I click on "New Channel", scan the QR code on 1ML.com, enter 100000 sat and press "Open Channel". Instead of a new channel I get the error message "2: ERROR from GRPC Stream for OpenChannel: peer is not connected"

![screenshot_20180710-191705_shango](https://user-images.githubusercontent.com/19550140/42526906-7cf2b068-8477-11e8-9824-c334d655febe.jpg) ![screenshot_20180710-191603_shango](https://user-images.githubusercontent.com/19550140/42526909-80316aa8-8477-11e8-830c-0850e90661db.jpg)

## Possible Solution or Best way to handle this problem
I can open this exact channel using `lncli` on my Raspberry Pi:
```
admin ~ ฿ lncli connect 02cf3cc45d8fee5055c4ba5a58fe22ae973685fa2cb43e2c5b6454eaa1d08066a8@54.84.35.4:9735
[lncli] rpc error: code = Unknown desc = already connected to peer: 54.84.35.4:9735
admin ~ ฿ lncli openchannel 02cf3cc45d8fee5055c4ba5a58fe22ae973685fa2cb43e2c5b6454eaa1d08066a8 100000
{
        "funding_txid": "69b98e70c551e5fec6663bb30f32958de9e1159b67a031ad7bdab840d35db96e"
}
```

**Comment by neogeno** [comment]
The latest build should be version 24 - can you confirm which build this is?

**Comment by Stadicus** [comment]
Using build 24, now it works... :-)
