### ISSUE TITLE
Connect with FQDM works only with lower case

### ISSUE THREAD

**Issue by Stadicus** [neogeno/shango-lightning-wallet#33]
- OS (Android/iOS)   **Android**
- Version of OS  **8.0.0**
- Device Make and Model   **Samsung Galaxy S9**
- Shango Version  ** Alpha Testing Build 23**
- Device ID **d340382c5ed4bfb5**
- LND version    **lnd v0.4.2-beta**

## Expected Behavior
When connecting to my own node, I enter the domain name incl. port and can connect. Domain names are not case sensitive, so even a mix of upper and lowercase characters should be ok.

## Current Behavior
If I connect with `Lightning.xxxxxxx.com` I get the following error:
![2018-07-11 22_04_42-window](https://user-images.githubusercontent.com/19550140/42596618-9b4a28ae-8556-11e8-852f-31fb4f29a2aa.png)

Connecting with `lightning.xxxxxxxx.com` works fine.
![2018-07-11 22_04_04-window](https://user-images.githubusercontent.com/19550140/42596623-9e823a98-8556-11e8-961d-6cb02f54912a.png)

## Possible Solution or Best way to handle this problem
Just use lower case... :-)

**Comment by neogeno** [comment]
fixed in build 25
