### ISSUE TITLE
Can't open channel with capacity over 4 digits

### ISSUE THREAD

**Issue by TomasHo** [neogeno/shango-lightning-wallet#34]
Thank you for trying out Shango Beta.   

Please submit your issues with the following information

- OS (Android/iOS)   iOS
- Version of OS  latest
- Device Make and Model   6S
- Shango Version  1,07, build 24
- Device ID (Look in Settings-About Shango)  1C66DAB2-F429-4F78-86D6-6A7A7EF7376A

## Current Behavior

When opening a new channel, the "Capacity in Satoshis" and "Remote deposit" fields will reset when 5th digit entered. I tried different combinations.
## Possible Solution or Best way to handle this problem

"SAT/byte fee" field works just fine, maybe look for differences.
I thing I noticed is that the Fee field does not have a thousands separator space.
Also, the regional settings can be an issue. Our decimal separator is a comma.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by neogeno** [comment]
Thanks this is a locale issue and will be fixed in the next build.

**Comment by neogeno** [comment]
Fixed in build 25
