### ISSUE TITLE
TCP Read Error when returning from background

### ISSUE THREAD

**Issue by JediWed** [neogeno/shango-lightning-wallet#36]
- iOS 11.4.1 
- Shango 1.07 (24) 
- iPhone 7   
- Device ID: 26DB670B-5338-40D9-99FF-68E2E5-005FED

When Shango is sent to the background and comes back from the background two error messages appear.

## Expected Behavior
No error message should appear

## Current Behavior
Error message appears :-)

## Steps to Reproduce
1. Start the (fully configured) app
2. Press home button (don't kill Shango)
3. Wait at least 30 minutes
4. Start Shango again

![img_8486](https://user-images.githubusercontent.com/9463106/43067531-e51bb8d4-8e67-11e8-8702-58f0e35db145.PNG)
![img_8487](https://user-images.githubusercontent.com/9463106/43067534-e7ac0982-8e67-11e8-9456-7f412f5f664d.PNG)

**Comment by neogeno** [comment]
Thank this should be fixed in the next build

**Comment by JediWed** [comment]
Eta for next build?

**Comment by neogeno** [comment]
Build 27 is being released in 24 hours that fixes this.
