### ISSUE TITLE
Suggestion: Request new address only if user wants to receive bitcoins

### ISSUE THREAD

**Issue by JediWed** [neogeno/shango-lightning-wallet#38]
Everytime the app starts it also requests a new address from backend (lnd)

> Aug 05 15:41:16 rv1025 lnd[20543]: 2018-08-05 15:41:16.206 [INF] RPCS: [newaddress] addr=3EuSiE....

Suggestion: App should only request a new address if the user creates a new invoice and presses "Bitcoin Request".

- iOS 11.4    
- iPhone X
- Shango v1.07 (24)  
- Device ID: 26DB670B-5338-40D9-99FF-68E2E5-005FED

**Comment by neogeno** [comment]
This will be fixed in Build 27 thank you for the feedback.
