### ISSUE TITLE
Instructions are not well formatted

### ISSUE THREAD

**Issue by JediWed** [neogeno/shango-lightning-wallet#40]
- iOS  
- 11.4.1
- iPhone X 
- 1.07 (28)
- 26DB670B-5338-40D9-99FF-68E2E5005FED

## Current Behavior

1. Modal Popup looks very ugly on the top on iPhone X.
2. Commands are starting with $. Copying them copies also $. But starting a command with $ does not work.
3. Sometimes (sporadic) close button title is not centered

## Possible Solution or Best way to handle this problem
1. Modal popup should be a little bit smaller and lower so that the status bar of iOS should not be on that modal popup
2. Remove starting $ from commands
3. Center Close title (this issue is very sporadic)

![img_0104](https://user-images.githubusercontent.com/9463106/43703565-61ddb66a-995d-11e8-9318-47d6be39b7d8.PNG)

**Comment by neogeno** [comment]
Decided the easiest way is to remove this screen and point to the official, more detailed instructions on the Github README. Let me know if you see any major issues with this.
