### ISSUE TITLE
Activity indicator is not centered on connect screen

### ISSUE THREAD

**Issue by JediWed** [neogeno/shango-lightning-wallet#41]
- iOS   
- 11.4.1
- iPhone X 
- 1.07 (28)
- 26DB670B-5338-40D9-99FF-68E2E5005FED

Activity indicator is not centered on connect screen

## Expected Behavior
Activity indicator should be centered

## Current Behavior
It's not centered

## Possible Solution or Best way to handle this problem
Center it

## Steps to Reproduce
1. Scan a QR code of your lightning node
2. Press connect

![img_0107](https://user-images.githubusercontent.com/9463106/43703721-0064f6a4-995e-11e8-8002-efcdc8386159.PNG)

**Comment by neogeno** [comment]
this was corrected with build 35
