### ISSUE TITLE
App crashes when scanning QR code for adding a node

### ISSUE THREAD

**Issue by christian1211** [neogeno/shango-lightning-wallet#44]
- OS (Android/iOS)   **Android**
- Version of OS  **LineageOS 14.1 - Android 7.1.2**
- Device Make and Model   **Xiaomi Redmi Note 3**
- Shango Version  **Version 1.0 Build 29**
- Device ID  **56377db67775da8b**

When I try to add a new node via QR code the app crashes without adding the node.

## Expected Behavior
- tap on "Scan QR"
- camera opens
- scanning QR code
- node added

## Current Behavior
- tap on "Scan QR"
- camera opens
- scanning QR code
- App crashes

## Steps to Reproduce
1. tap on "Scan QR"
2. scan QR code

**Comment by neogeno** [comment]
Hi did this work in previous build ?

**Comment by christian1211** [comment]
Hello,
it's the first build I tried so I cannot say if it worked in older versions, sorry.

**Comment by christian1211** [comment]
I changed my OS and updated the app:

OS (Android/iOS) **Android**
Version of OS **xiaomi.eu MIUI 9.5 - Android 6.0.1**
Device Make and Model **Xiaomi Redmi Note 3**
Shango Version **Version 1.0 Build 32**
Device ID **c7423a159bf85ad1**

With the new Version the app does not crash any more but I'm still not able to add my node. Screenshot attached.

Port 10009 is open and rcplisten is entered in lnd.conf.
![shango](https://user-images.githubusercontent.com/35952837/44954612-ceab4300-aea4-11e8-948b-620ead9e259d.jpg)

**Comment by neogeno** [comment]
Can you try to Scan this code and see if you can connect to my example Main Net Node?
<img width="1132" alt="qr" src="https://user-images.githubusercontent.com/4373046/44959114-6bf58e00-af1c-11e8-9eba-9539183a3ae0.png">

**Comment by christian1211** [comment]
This works fine. So it seems to be a problem with my node?

**Comment by neogeno** [comment]
Most likely a networking issue. Could it be that your ISP or router may be blocking traffic of certain types ?
