### ISSUE TITLE
QR scan "Error reading QR code" Samsung galaxy S8

### ISSUE THREAD

**Issue by hopitas** [neogeno/shango-lightning-wallet#47]
- Android
- 8.0.0  
- Samsung Galaxy S8  
- Shango Version: 1.0 Build 32
- Device ID 5b5c48a34e78c7a5

I generate QR following the instructions, but when I try to scan it, I just get QR-code error.

## Expected Behavior
Get ip/server macaroon and server tls cert from QR-code

## Current Behavior
Error Processing QR -message

**Comment by hopitas** [comment]
Ok found out why this didn't work. My terminal screen was probably too big... I just used smaller screen until reading worked.

**Comment by dawiepoolman** [comment]
hmm, maybe it is not so stupid.. I am struggling too using my Samsung S7 
I am following Stadicus's [guide] (https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_68_shango.md) for LND 0.5

How exactly did you reduce the QR size?

**Comment by hopitas** [comment]
I'm using Ubuntu Bash for windows as a terminal. I cliked window properties on upper left corner menu and selected smaller font size few times, maximized the window after that. When the maximized terminal window didn't fill my monitor screen, I was able to scan the QR. Maybe with bigger screen the QR gets distorted/misses some pixels etc?

**Comment by dawiepoolman** [comment]
Thx for the detail suggestion.

Unfortunately mine still does not take.

I did the following in my Windows Putty SSH terminal:
1) Open Putty
2) Select Appearance from the Window node on navigation tree in the in left hand panel.
3) Click the Change button in the Font settings section
4) Select smallest available font size size 8 and connect the session
5) Generate QR for LND v0.5 as per guide

Still not processing the QR for me.

**Comment by dawiepoolman** [comment]
Hi neogeno

I have used the latest LND 0.5 command on Stadicus's [guide](https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_68_shango.md)

`echo -e "$(curl -s ipinfo.io/ip),\n$(xxd -p -c2000 ~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon)," > qr.txt && cat ~/.lnd/tls.cert >>qr.txt && qrencode -t ANSIUTF8 < qr.txt`

I get error: "Error processing QR" on the Shango app after a timeout i.e. it takes about a minute trying to  read the QR and eventually pops the error.

It could be that the macaroon dir is incorrect on the guide as well?

**Comment by neogeno** [comment]
Are you running a Testnet or Mainnet node? For example, the directory would be /chain/bitcoin/testnet for your macaroon if you were running testnet . Also type in `cat qr.txt` and verify that the IP, macaroon in hex format and TLS certificate (3 fields separated by a comma) should be present in the file. As a last resort, what you can do is use the command `xxd -p -c2000 <filename>` for both the admin.macaroon and tls.cert file, and copy/paste it manually into the fields in Shango to connect. Let me know if you managed to solve this problem and how you did it. Thanks.

**Comment by dawiepoolman** [comment]
Thx for great suggestions.  I tried them all.  Even reinstalled.
It gave a critical connection error 4 for a short amount of time after I pasted the ip, macaroon and tls details manually. Now the screen is stuck on "lnd wallet locked" and I cant close it to retry.  When I close and reopen the app it opens on the "lnd wallet locked" screen immediately.  When I put in my wallet password it fails to unlock so it seems like the connection settings did not save after the connection error, or maybe the settings are somehow invalid? 
I am on mainnet.

**Comment by neogeno** [comment]
@dawiepoolman Please try with the latest version 1.08.x out later today and let me know.

**Comment by dawiepoolman** [comment]
So I tried with version 1.08 build 38 (the latest right?)
No luck unfortunately.
First when I open the app it immediately pops up screen overlay: LND WALLET LOCKED.
I then click on Abort and click through to Settings (the lock screen keeps popping up)
I tried scanning QR again - Not scanning.
I copied the settings manually for each field and then got error:
Critical Problem!
ERROR Connecting to the LND Service at *My public IP*
Check network connection and settings and try again later
Ref:Error: 14 UNAVAILABLE: Connection Failed

**Comment by neogeno** [comment]
@dawiepoolman Please try the following and let me know how it goes.

1. Goto Settings Tab - Terminate Node and burn baby burn - this will terminate the cloud node that was created incorrectly by the older versions

2. Shango will go into Setup Wizard mode. Choose Connect to your Own Private server and SCAN this QR code to test if it works:

![screen shot 2018-10-12 at 11 32 19 am](https://user-images.githubusercontent.com/4373046/46887534-be2aa880-ce12-11e8-9394-e84ac0428cee.png)

3. Click through the setup wizard till you see the Rocket Ship and Done screen. You are now setup to only connect to Private nodes and should not see the unlock screen anymore.

Once connected, Verify you are connected to my MAIN NET test node and use the Receive Button in the Transfers tab to show a Wallet Address QR code. (FYI: There is zero balance or transactions on this node.)

If you can successfully connect to my node, the problem lies with your network connectivity to your node, router/firewall etc settings and you should ensure you can connect externally using the `lncli` command first before attempting to use Shango.

Hope this helps and let me know you go.

**Comment by dawiepoolman** [comment]
@neogeno thank you for the great instructions

I got error:
Error Processing QR
Cannot get valid Macaroon

I have saved the QR code to my laptop and opened it to be full screen to try help the scanning.  Maybe the Samsung S7 camera cannot process such a compact QR code?

**Comment by neogeno** [comment]
@dawiepoolman I have tried it with older Note4 devices running Android 6 and it still worked. Here, try to paste in the values manually first:

IP: 
34.232.232.166

Macaroon:
0201036c6e6402bb01030a101ae4d99183feecc080f1503e1a9e46a81201301a160a0761646472657373120472656164120577726974651a130a04696e666f120472656164120577726974651a170a08696e766f69636573120472656164120577726974651a160a076d657373616765120472656164120577726974651a170a086f6666636861696e120472656164120577726974651a160a076f6e636861696e120472656164120577726974651a140a0570656572731204726561641205777269746500000620427fd0126bfeabb09cd4b09f25a48de159020f6fb9bd859ab9b96b774cbf07eb

TLS:
2d2d2d2d2d424547494e2043455254494649434154452d2d2d2d2d0a4d4949434f7a43434165476741774942416749514378616d7a646b32616a7267344a3742564744786c54414b42676771686b6a4f50515144416a41364d5238770a485159445651514b45785a73626d5167595856306232646c626d56795958526c5a43426a5a584a304d526377465159445651514445773570634330784e7a49740a4d6a59744e6930794d7a4165467730784f4441354d5463774d6a4d774d7a6861467730784f5445784d5449774d6a4d774d7a68614d446f78487a416442674e560a42416f54466d78755a434268645852765a3256755a584a686447566b49474e6c636e5178467a415642674e5642414d54446d6c774c5445334d6930794e6930320a4c54497a4d466b77457759484b6f5a497a6a3043415159494b6f5a497a6a304441516344516741456e4564596a376c784f514b514567327633722b434749566b0a746a45456f51733270726c4353783362646c6b73336e626242787250563355484265464e704632482b6e346e574a32374a536b45384664673742356761714f420a794443427854414f42674e56485138424166384542414d434171517744775944565230544151482f42415577417745422f7a43426f515944565230524249475a0a4d49475767673570634330784e7a49744d6a59744e6930794d34494a6247396a5957786f62334e306767317a614746755a3239686348417559323974676752310a626d6c3467677031626d6c346347466a613256306877522f414141426878414141414141414141414141414141414141414141426877537347675958687753730a45674142687753734551414268775373457741426878442b67414141414141414141773867762f2b764d58796878442b674141414141414141414243742f2f2b0a7435304c68775169364f696d4d416f4743437147534d343942414d43413067414d45554349514367327765533033455872534b4c63444e64476e77764b3449430a2f39376c704e47556870383666614f3466414967535a6351416c6952614b696641644c333042482f7774626e50642f2b467864645477546e587a647a2f6d303d0a2d2d2d2d2d454e442043455254494649434154452d2d2d2d2d0a

If connection works here, at least you can know the app works. Let me know.

Thanks.

**Comment by neogeno** [comment]
@dawiepoolman So I need to investigate why your device can't scan the QR. In the main net release, I shall make the QR less 'dense' by omitting the TLS certificate. Hopefully, this will help in you case.

**Comment by dawiepoolman** [comment]
Thanks that should help . Looking forward
