### ISSUE TITLE
"Connect to other LND Nodes" forgets the connection after app restart

### ISSUE THREAD

**Issue by hopitas** [neogeno/shango-lightning-wallet#48]
- OS Android   
- Version 8.0.0  
- Device Samsung S8
- Shango Version  1.0, Build 35
- Device ID 5b5c48a34e78c7a5  

With new version, Shango doesn't start with previously connected own node, instead starts default node on restart.

Previously Shango started with once configured other node setup by default.

**Comment by neogeno** [comment]
This is corrected in v1.08.2
