### ISSUE TITLE
Error when connecting to a not synced node

### ISSUE THREAD

**Issue by TomasHo** [neogeno/shango-lightning-wallet#50]
- OS (Android/iOS)   iOS
- Version of OS  latest
- Device Make and Model   
- Shango Version  1.08.3
- Device ID (Look in Settings-About Shango)  1C66DAB2-F429-4F78-86D6-6A7A7EF7376A

It seems that when connecting to a LN wallet running on a 0.5 LND that is unlocked but not synced, it causes a error message and wallet gets locked.
## Expected Behavior

Dedicated error message
## Steps to Reproduce

1.
2.
3.
4.

**Comment by neogeno** [comment]
Please use latest build and re-open if this is still the case
