### ISSUE TITLE
Android app keeps hanging on first startup

### ISSUE THREAD

**Issue by CodingMuziekwijk** [neogeno/shango-lightning-wallet#53]
Thank you for trying out Shango Beta.   

Please submit your issues with the following information

- android
- 8.0
- one plus 3  
-  version 1.08
- can't get to settings 

## Expected Behavior
finish restoring state and startup

## Current Behavior
Keeps hanging on restoring state

## Possible Solution or Best way to handle this problem
?? 

## Steps to Reproduce
1.download app (from playstore)
2.startup

**Comment by CodingMuziekwijk** [comment]
I already tried reinstalling, but that didn't work.

**Comment by neogeno** [comment]
Please terminate your node from the settings menu and try again.
