### ISSUE TITLE
QR Scan Fails if Whitespace Removed from Text

### ISSUE THREAD

**Issue by bcwhite0** [neogeno/shango-lightning-wallet#54]
Please submit your issues with the following information

- OS (Android/iOS)   Android
- Shango Version  1.08

echo -e "$(curl -s ipinfo.io/ip),\n$(xxd -p -c2000 ~/.lnd/data/chain/bitcoin/$NETWORK/admin.macaroon)," > qr.txt && cat ~/.lnd/tls.cert >>qr.txt

When scanning a QR code under "Connect to other LND Nodes", the scan will fail if the QR code generator has stripped linefeeds from the text.  It shouldn't but apparently some do.

There are already comma separators and BEGIN/END certificate markers so the absence of whitespace should be acceptable.

**Comment by neogeno** [comment]
The next build will remove the need to scan the TLS certificate so this whitespace issue can be avoided.

**Comment by neogeno** [comment]
Please use the latest version of the app and let me know if this still occurs
