### ISSUE TITLE
Can't Back Out of Incorrect Password

### ISSUE THREAD

**Issue by bcwhite0** [neogeno/shango-lightning-wallet#56]
OS (Android/iOS):    Android
Version of OS:          9 (Pie)
Device Make and Model:  Pixel 3XL
Shango Version:  1.08

After providing a LND password and tapping "Unlock Wallet" and getting the error, "Minor Problem: invalid passphrase," there is no way out.  The buttons are greyed out and the "back" button does nothing.

## Expected Behavior
There should be a way to retry.

## Current Behavior
Stuck.  Have to force-close the app.

## Steps to Reproduce
1. Enter a bad passphrase when unlocking the wallet.
2. See error dialog and "OK" it.
3. Now stuck.

**Comment by mattrolightning** [comment]
Same issue.

**Comment by neogeno** [comment]
This is fixed with latest build
