### ISSUE TITLE
Can't past macaroon

### ISSUE THREAD

**Issue by mattrolightning** [neogeno/shango-lightning-wallet#57]
- iOS 12  
- iPhone 7S   
- Latest Shango version  

When trying to paste the macaroon into the window in security and privacy settings, the keyboard pops up hiding the window and making it impossible to paste.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/43560996/47121811-27ab1c80-d242-11e8-8df1-331f59b9fe8d.png">

**Comment by neogeno** [comment]
This has been fixed by latest 1.08.3 Build 2 or greater
