### ISSUE TITLE
Android galaxy S5 crashes on launch

### ISSUE THREAD

**Issue by chseeling** [neogeno/shango-lightning-wallet#59]
- OS (Android/iOS)  
Version 6
- Version of OS  
- Device Make and Model  
Samsung galaxy s5
- Shango Version  
1.08.7
- Device ID (Look in Settings-About Shango)  
Not reachable

## Expected Behavior

Lauch successfully

## Current Behavior

Freshly installed app crashes 2-5 sec after launch showing screen with a number of spinners.
No other details are show.

## Possible Solution or Best way to handle this problem

Retried lauch a number of times and reinstalled but crash behavior  persist 

## Steps to Reproduce

1. Install using google play
2.launch
3.
4.

**Comment by neogeno** [comment]
@chseeling please try with the latest version build 42 and let me know

**Comment by chseeling** [comment]
I reinstalled the new build and startup works fine now.
Thanks Patrick.
