### ISSUE TITLE
Payment error even though payment went through

### ISSUE THREAD

**Issue by PatrickLemke** [neogeno/shango-lightning-wallet#6]
- iPhone 7
- iOS 11.3.1
- Shango 1.07 (8)
- 34F26EC5-2E8E-4160-BB86-3DA05F23D261

## Expected Behavior

Error message should not appear

## Current Behavior

This error message is shown: 
![payment issue](https://user-images.githubusercontent.com/2649936/40886557-74b5816e-673a-11e8-829f-70dc4357025b.jpg)

## Steps to reproduce
Make a payment with lightning

**Comment by neogeno** [comment]
Is this build number 7 or 8?

**Comment by PatrickLemke** [comment]
Both

**Comment by neogeno** [comment]
Could you try to delete the app and re-install build 8?

**Comment by PatrickLemke** [comment]
Yes, it works now!
