### ISSUE TITLE
Not possible to send onchain payments

### ISSUE THREAD

**Issue by JediWed** [neogeno/shango-lightning-wallet#62]
- iOS 12.1  
- iPhone X
- Shango 1.08.6 Build 12

## Expected Behavior
- Bitcoins are sent onchain

## Current Behavior
- Onchain Bitcoins are NOT sent

## Possible Solution or Best way to handle this problem
- Commit Bitcoin Address to Backend/LND case sensitive instead of lowercase in case of onchain payments

Log: RPCS: [sendcoins] addr=3268balunrbrqiav5sgwhqbymdeeeqqkby, amt=0.001429 BTC, sat/kw=2798

This can't work because upper case letters were transformed into lower case

## Steps to Reproduce

1. Touch "Transfer"-Tab
2. Touch "+"-Button
3. Touch "New Payment"-Button
4. Scan P2SH Bitcoin Address (e.g. 3268BaLunrbRqiav5SGWhqbymdeEEqQKby)
5. Enter number of satoshis
6. Touch "Pay"

**Comment by neogeno** [comment]
Thanks for the feedback. I shall fix this in the next build

**Comment by neogeno** [comment]
Fixed in build 55. Please open again if persists.
