### ISSUE TITLE
Feedback on Channel Close on IOS shows "Opened"

### ISSUE THREAD

**Issue by AmazingDroopy** [neogeno/shango-lightning-wallet#64]
- OS: iOS   
- Version of OS: 12.1.2  
- Device Make and Model: iPhone 8Plus   
- Shango Version: 1.08.6 build 12
- Device ID 07B32F5B-71E9-4624-933D-9D162A-9D1315  

When closing a Channel, the green feedback in the top shows 2 messages.
The second message says: "Channel Opened" when in fact it was just closed. 

## Expected Behavior
Message: "Channel Closed"

## Current Behavior

Message: "Channel Opened"

## Possible Solution or Best way to handle this problem

Change feedback phrase in the code.

## Steps to Reproduce

1. Close an active Channel
2. Watch the feedback messages in green in top of app.
3.
4.

**Comment by neogeno** [comment]
Fixed in latest build 52 - please try and re-open if it still exists.
