### ISSUE TITLE
Connection / authentication error

### ISSUE THREAD

**Issue by MrPaz** [neogeno/shango-lightning-wallet#68]
This is connectivity issue/troubleshooting/help, but fwiw I'm on Android 9 with latest Shango version available in Google Play.  Hoping you can help me get set up / and create a troubleshooting post for others googling this same problem in future.

So I used [Stadicus](https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_68_shango.md)' guide to make a bitcoin/lightning node on my pi.  Now I followed both his and your guides to setting up Shango.  However, when I get to final step of trying to connect, it fails.  At final step in your guide, `--rpcserver=<YOUR PUBLIC IP> getinfo` , I get the following error: 
`[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for 127.0.0.1, ::1, 192.168.1.2, fe80::263c:7249:a126:7f33, not XX.XX.XX.XX"`

Similarly, in Shango once I scan the QR and click connect I get error:
Connect Failed: Most likely an SSL certificate authentication failure.  Please check your connection IP/host match your certificate domain and IP values.

So what am I missing??  I have port 10009 open on router.  lnd.conf is updated with info in your guide and my external IP from `curl icanhazip.com` , ufw updated to allow 10009, deleted tls files and rebooted to create new ones, copied new certs to appropriate directories.  Thanks.

**Comment by pardus79** [comment]
I had the same problem and figured out my issue was something as simple as putting the `rpclisten=0.0.0.0:10009` and `externalip=[your ip]` settings in the wrong place in the lnd.conf file.

They both need to be in the `[Application Options]` section. Else they won't be processed when lnd starts.

**Comment by neogeno** [comment]
Closed as it relates to an older version
