### ISSUE TITLE
BTCPay Server LND Node

### ISSUE THREAD

**Issue by slack333** [neogeno/shango-lightning-wallet#69]
Hi! There is a way that I could connect Shango to my BTCPay Server LND Node?
I couldn't find anything to how to do it!

**Comment by NicolasDorier** [comment]
They need to fix this: https://twitter.com/NicolasDorier/status/1082499689721716736

**Comment by neogeno** [comment]
Will add:

ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256

in next release

**Comment by NicolasDorier** [comment]
@neogeno let me know when it release so I can add shango to the list of compatible wallet in our gRPC details page.

**Comment by neogeno** [comment]
Added to build 54 just now. Closing this for now, please do add Shango on the Grpc page and re-open if any further issues.
