### ISSUE TITLE
Be able to change amount in LN request with value 0

### ISSUE THREAD

**Issue by J4K0B** [neogeno/shango-lightning-wallet#76]
Thank you for trying out Shango Beta.   

Please submit your issues with the following information

- OS (Android/iOS)   Android 
- Version of OS  Android 8.0.0
- Device Make and Model   ZTE Axon 7 ZTE A2017G
- Shango Version  1.08.11
- Device ID (Look in Settings-About Shango)  6b6f9bcb2726b24f

## Expected Behavior
After scanning an invoice with value / amount of 0, I should be able to change the value.

## Current Behavior
I cannot change the value. I need to be able to do this for donations on tippin.me for example.

## Possible Solution or Best way to handle this problem
In src/components/paycard.js in onSuccess(qr) add an if statement which checks if the paymentRequestResponse.numSatoshis equals 0, if so don't disable the editing.

## Steps to Reproduce
1. try to tip someone at tippin.me
2. scan the qr invoice
3. now you can't specify the amount you want to donate to the person

**Comment by J4K0B** [comment]
(unrelated) Also, why don't you open source the whole source code and not just the component src?

**Comment by neogeno** [comment]
Will be tidying up and release the entire code base along with contribution guidelines

**Comment by neogeno** [comment]
This was fixed in Build 54 now. Please let me know if it works!
