### ISSUE TITLE
Connecting to DIY LND Node

### ISSUE THREAD

**Issue by RyanSepio** [neogeno/shango-lightning-wallet#78]
Thank you for trying out Shango Beta.   

Please submit your issues with the following information

- Android
- 9  
- Google Pixel 3   
- 1.08.11  
- Device ID (Look in Settings-About Shango)  

## Expected Behavior
Trying to connect to hosted LND.  Confirmed port 10009 is open.  

## Current Behavior
When generating the QR code in Step 2 it shows an error "./.lnd/tls.cert: No such file or director

I am lost here because I don't understand the tls.cert and macaroon components.   Why is the cert not found on my node?

**Comment by neogeno** [comment]
Please update to the latest version and use the latest QR code command
