### ISSUE TITLE
Cannot connect to AWS or Node, asks to reboot

### ISSUE THREAD

**Issue by OfficialBigAl** [neogeno/shango-lightning-wallet#79]
Thank you for trying out Shango Beta.   

Please submit your issues with the following information

- OS (Android/iOS)   Android
- Version of OS  8.0.0
- Device Make and Model   Huawei Honor 9 Lite
- Shango Version  1.08.11 (build 46)
- Device ID (Look in Settings-About Shango)  3a3d07b4c7ccbca7

The local PI node I was connected to failed and upon rebuilding, Shango would not reconnect.

## Expected Behavior
I have tried rebooting, disconnecting and Nuking the Shango configuration but with no change.
Even uninstalling and reinstalling does not reset the config.

## Current Behavior
Opening the app produced the below error and it's not responsive.

## Steps to Reproduce
1. Open Shango application...
2.
3.
4.
![Screenshot_20190422-113637](https://user-images.githubusercontent.com/46918332/56497073-00385380-64f4-11e9-9598-0c09c1d00f50.jpg)

**Comment by neogeno** [comment]
Sorry I have revamped the backend to improve security. Please download the latest release in May to fix this.
