### ISSUE TITLE
Can't download from Android play store, early access is full.

### ISSUE THREAD

**Issue by BladeMcCool** [neogeno/shango-lightning-wallet#80]
Android 7, Moto G4plus, went to play store, found the listing for the Shango Lightning Wallet from NeoGeno, it says Early Access on it, and when you click it to get details you get a message saying "The early access program is currently full. Space may open up later". There is no option to install.
Thank you for trying out Shango Beta.   

Is there any other way to install it?

**Comment by neogeno** [comment]
It's open now
