### ISSUE TITLE
Doesn't go pass "Spinning up your shiny new LND node"

### ISSUE THREAD

**Issue by BrencelJ** [neogeno/shango-lightning-wallet#82]
- Android
- Verizon of OS: 8.0.0 
- One plus 3
- Shango Version: Latest on Google play (1.08.6 Build 55) 
- Device ID - can't get there

## Expected Behavior
It should go pass it and than I would be able to use it. 

## Current Behavior
Gets stuck on "Spinning up your shiny new LND node"

## Possible Solution or Best way to handle this problem
Since I have my own LND node in RP I would prefer to be able to chose that and not go trough this steps. 

## Steps to Reproduce
When I do the first setup. I tryed to remove it and install it again and cleared data rebooting phone bit nothing works it says it will take 35 seconds but it doesn't finish after longer time period. (photos as to show the time waited and I said I don't want to wait longer) 
![Screenshot_20190628-075225](https://user-images.githubusercontent.com/7051928/60321346-ddf00580-997c-11e9-8dcb-8cafa08e8de5.jpg)
![Screenshot_20190628-081352](https://user-images.githubusercontent.com/7051928/60321347-ddf00580-997c-11e9-9f0a-ed9d24ebd0fb.jpg)

**Comment by neogeno** [comment]
Thanks for reporting this. The SSL cert expired so had to setup an auto-renewal process for this. Please try again now. In the next release, I will add a new workflow to connect to your self hosted node in a quicker manner.
